# Introducción: Pandas

Antes de introducir el concepto de Dataframes es importante dar paso a un componente primordial hoy día en el ecosistema de Python Y son las librerías o paquetes desarrollados por terceros, si bien en la parte I, se habló de varias de las funcionalidades built-in en Python, ahora es el momento de introducir una de las librerías más famosas y su nombre es Panda, la cual nos sirve para desarrolladas programas que permitan analizar y manipular datos en gran escala.  Pero antes de llegar al concepto de Dataframe es importante entender los siguientes temas:

1.	Numpy Arrays
2.	Series

## Teoria: Numpy Array

Numpy es una libreria o paquete desarrollado por terceros y que se usa extensivamente en proyectos de machine learning. Para la parte dos estaremos usando la libreria que ya viene instalada dentro del proyecto de Anaconda, en este caso dirijase a la parte de instalacion y creacion del ambiente virtual.

En este parte del libron estaremos hablando de uno de las caracteristicas de la libreria mas populares y que tienen por nombre Numpy Array, veran la importancia de esta funcionalidad a lo largo del libro y porque de uso en el universo cientifico de Python.

Para empezar, importaremos la libreria y creamos nuestro primer Numpy Array:

* Aqui la idea es mencionar las ventajas y caracteristicas comparado con las listas que tienen los arreglos de numy
* La operacion de suma, adicion, resta y multiplicacion


In [3]:
# Se importa la libreria numpy y se renombra como es de constumbre a np. Por lo general el acronimo para la libreria numpy es np.
import numpy as np

# Se crea el arreglo de numeros del 1-10
nums = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Se imprime el valor del arreglo
nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Vale la pena mencionar que un array de Numpy se parece mucho a una lista de Python.** La diferencia principal radica en el tipo de operaciones de orden matematico que se pueden realizar sobre un arreglo de Numpy y las listas nativas de Python.

Miremos esto de que se trata intentemos sumar los elementos de una lista nativa Python:

In [4]:
# Lista nativa de python, con los numeros del 1-10
nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Suma de los elementos de la lista
nums + nums

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
Como se evidencia los elementos de la lista se duplicaron en una lista de mayor tamano, Pasara lo mismo con un arreglo de Numpy? Veamoslo:

In [5]:
import numpy as np

# Se crea el arreglo de numeros del 1-10
nums = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Se suman los elementos del arreglo de Numpy
nums + nums

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Se mantuvo el tamano de la lista, pero sus elementos fueron sumados, y es aqui el potencial y la simpleza de los arreglos de Numpy, y porque de uso en el mundo cientifico, miremos su codigo equivalente con las lista de Python:

In [8]:
# Lista por compresion con adicion de sus elementos
[x + x for x in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

No creemos que sea complicado estar creando listas de *comprension de python* pero claramente se reducirian las lineas de codigo en nuestro programa.

Veamos que pasaria con las demas operaciones, empezando con la resta:

In [9]:
import numpy as np

# Se crea el arreglo de numeros del 1-10
nums = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Se suman los elementos del arreglo de Numpy
nums - nums

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Con el arreglo de Numpy obtendriamos 0, y tiene todo el sentido, ya que $0-0 = 0$, $1-1 = 0$, $...$, $n-n=0$, para una arreglo numpy de n tamanos, ahora que pasaria con la multiplicacion, pero antes que pasaria con la resta de una lista nativa de Python:

In [10]:
nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
nums - nums

TypeError: unsupported operand type(s) for -: 'list' and 'list'

Claramente el operador de resta  $(-)$ no es soportado por las listas nativas, y ahora sigamos con la multplicacion:

In [13]:
import numpy as np

# Se crea el arreglo de numeros del 1-10
nums = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Se suman los elementos del arreglo de Numpy
nums * nums

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Obtendriamos el comportamiento similar y el esperado al de las demas operaciones, como tambien seria el caso de la division:


In [14]:
import numpy as np

# Se crea el arreglo de numeros del 1-10
nums = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Se suman los elementos del arreglo de Numpy
nums / nums

/tmp/ipykernel_1872/3848183508.py:7: RuntimeWarning: invalid value encountered in true_divide
  nums / nums


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Notemos que, si bien se opero la division en la mayoria de los elementos del arreglo en el primero $0/0$ nos arrojo un error, ya que estamos tratando de realizar una division sobre $0$, la cual no es soportada, pero a nuestro favor los demas elementos lograron ser divisibles por su mismo elemento obteniendo en todos los demas casos $1.0$.

Si bien las listas de comprehension de Python podrian ayudarnos a emular estas operaciones incluidas nativamente sobre la libreria de Numpy, evidentemente no seria posible si quiero operar mas de dos listas a la vez, veamos el ejemplo:

In [22]:
# Se importa la libreria de Numpy
import numpy as np

# Se genera un arreglo de Numpy con numeros aleatorios del 1-10 y de tamano 10.
x = np.random.choice(10, 10)

# Se realiza la misma operacion sobre y
y = np.random.choice(10, 10)

# El resultado dado por la multiplicacionde estos dos arreglos seria
x * y

array([ 0, 56, 56, 35, 35,  2,  0, 18, 54, 42])

Ahora pensemos por un segundo que nuestro arreglo de numpy es muy grande, como por ejemplo:

In [26]:
x = np.random.choice(10, 100000)
y = np.random.choice(10, 100000)

x * y

array([18, 18,  0, ..., 40,  0, 15])

Y magicamente Numpy multiplico un arreglo de $100000$ elementos en un abrir y cerrar de ojos. Con esto vemos el potencial matematico de la libreria comparado con las funciones nativas de Pytho.



## Teoria: Series

Antes de hablar de *Dataframes* es importante que hagamos un pequeno repaso de **Series**, con el cual empezaremos a interactuar con la libreria de Pandas, al mismo tiempo que nos iremos ganando confianza para abordar los temas interesantes del universo de la manipulacion de datos tipos tabulares.

Que es una Serie? Que seria una Serie en el universo de los pandas? Como se crea una Serie? Veamos las respuestas a estas preguntas:



In [32]:
# Se importa la libreria de Pandas
import pandas as pd

# Se crea un diccionario nativo de Python (Como lo vimos en el libro 1)
proteinas = {'Gluten': 'Vegetal', 'Gelatina': 'Animal', 'Queratina': 'Vegetal', 'Pectina': 'Vegetal', 'Colágeno': 'Vegetal' };

# Se crea una serie de proteinas de panda a partir del diccionario de proteinas
serie_de_proteinas = pd.Series(proteinas)

# Se imprime la serie creada
serie_de_proteinas

Gluten       Vegetal
Gelatina      Animal
Queratina    Vegetal
Pectina      Vegetal
Colágeno     Vegetal
dtype: object

Como ven, se imprimio la serie creada a partir de las proteinas, con sus respectivos valor en la columna, ahora bien podriamos manipular la serie como lo hicimos con las listas nativas de Python miremos como se haria:

In [43]:
print(f'Tipo de proteina de Gluten: {serie_de_proteinas[0]}');
print(f'Fila 2 de la serie de proteinas: \n{serie_de_proteinas[1:2]}')
print(f'Indexacion del final al principio, en este se excluiria el Colágeno: \n{serie_de_proteinas[:-2]}')


Tipo de proteina de Gluten: Vegetal
Fila 2 de la serie de proteinas: 
Gelatina    Animal
dtype: object
Indexacion del final al principio, en este se excluiria el Colágeno: 
Gluten       Vegetal
Gelatina      Animal
Queratina    Vegetal
dtype: object


Como vimos, acceder a los elementos de la *serie* se logra de lac misma forma que como lo hicimos con las listas. Pero a veces es necesario manipular los elementos claves *(Keys)* de una seria, de hecho podriamos acceder a los tipos de proteinas usando las claves de la serie, pero veamoslo con un ejemplo:

In [45]:
# Imprive el tipo de proteina para el elemento cuya clave es Gelatina
serie_de_proteinas["Gelatina"]

'Animal'

In [46]:
# Imprime la lista de elementos clave de una serie
serie_de_proteinas.index

Index(['Gluten', 'Gelatina', 'Queratina', 'Pectina', 'Colágeno'], dtype='object')

Ahora bien, que tal si pensamos que una Serie de la libreria de Pandas es o posee algunas de las caracteristicas de los arreglos de Numpy, Podria ser esto posible? Miremos que pasaria si tenemos una serie de numeros aleatorias y asumamos que son operables como lo vimos mas arriba:

In [48]:
# Se importa Panda y Numpy (sigamos la convencion de nombres que ya establecimos)
import pandas as pd
import numpy as np

# Se crean dos series a partir de un arreglo de numpy de numeros aleatorios
a = pd.Series(np.random.rand(10))
b = pd.Series(np.random.rand(10))

# Se imprime la serie con su respectivo resultado despues de la operacion de adicion
a + b

0    0.827832
1    0.641650
2    1.393000
3    0.671700
4    0.677049
5    0.435522
6    0.760107
7    0.811108
8    1.257118
9    1.730951
dtype: float64

Inicialmente la suma funciono de la misma forma que los arreglos de Numpy, pero esta vez lo hicimos sobre la serie, eventualmente podriamos mezclar indexacion y multiplicacion al mismo tiempo para lograr obtener una nueva serie con nuestro propio sabor veamos este ejemplo:

In [52]:
a[1:] * b[:-1]

0         NaN
1    0.101402
2    0.481464
3    0.088272
4    0.104572
5    0.042915
6    0.012857
7    0.078402
8    0.313555
9         NaN
dtype: float64

Obtuvimos la nueva serie, y de paso algunos *NaN* o *(Not a Number)* porque algunos elementos de las series no concordaron los indexes. Lo interesante de este ejemplo es que pudimos explorar el potencial de los arreglos de Numpy y las Series de Pandas para hacer calculos matematicos.

*Si bien en este ejemplo usamos arreglos de Numpy, las series se podrian definir a partir de arreglos nativos de Python*

* Aqui la idea es mencionar las propiedas y caracteristicas de la serie de la libreria de pandas
* Usar el metodo de get, index y mostrar como se manipulan la series por porciones (split)

In [ ]:
import panda as panda
> point_dict = {"Bulgaria": 45, "Romania": 43, "Israel": 30,
"Denmark": 42}

Luego terminar con un ejemplo de numpy y pandas para continuar con DataFrames


## Teoria: Dataframes:


Ya hablamos de los arreglos de Numpy, vimos un poco las Series de la libreria Pandas y ahora que? Que sigue? Si ya vimos algunas de las funcionalidades mas relevantes de ambas librerias, pues bien los Dataframes son quizas mucho mas relevantes y emocionates comparada con las caracteristicas mencionadas con anterioridad.

Hablaremos de Dataframes en lo que resta de la parte dos y empezaremos pensando que un Dataframe es como una hoja de calculo, si como un Excel o como un google sheet, y porque no tambien podriamos visualizar como una base de datos compuesta de filas y columnas, a la final son un objeto que mantiene dicha estructura y que es manipulable de forma amigable.

Creemos un data frame a continuacion:


* Definicion y conceptos
* Ejemplo de construccion del dataframe (ideas del dataframe)
* Ejemplo de manipulacion, indexacion, columns,  etc
* Operaciones matematicas por filas y por columnas
* Otros metodos como add, pop, del, etc
* Iteracion sobre los dataframes
* Mezcla, Union y Concatenacion
* Los metodos mas relevantes

In [57]:
# Se importa la libreria de Pandas
import pandas as pd

# Sean dos arreglos y continuemos con el ejemplo de las proteinas y su tipo
nombre_proteinas = ['Gluten', 'Gelatina', 'Queratina', 'Pectina', 'Colágeno']
tipo_proteinas = ['Vegetal', 'Animal', 'Vegetal', 'Vegetal', 'Vegetal']

# Ahora se define un diccionario que relacione los nombres y las proteinas
proteinas_dic = { "nombre": nombre_proteinas, "tipo": tipo_proteinas }

# Se contruye el dataframe a partir del diccionario
proteinas_df = pd.DataFrame(proteinas_dic)

# Se imprime el dataframe
proteinas_df

nombre     tipo
0     Gluten  Vegetal
1   Gelatina   Animal
2  Queratina  Vegetal
3    Pectina  Vegetal
4   Colágeno  Vegetal

Notemos la visualizacion del DataFrame tal cual la descripcion incial de le dimos, un objeto con columans y filas.

Esta no es la unica forma de definir un dataframe, podemos un jugar un poco con ella e incluso crear dataframes a partir de arreglos de numpy como lo vemos a continuacion:

In [61]:
# Se importa la libreria de Pandas
import pandas as pd

# Se crea el arreglo de proteinas
proteinas = [
    ('Gluten', 'Vegetal'),
    ('Caseina', 'Animal'),
    ('Albúmina','Vegetal'),
    ('Colágeno', 'Vegetal'),
    ('Gelatina', 'Animal'),
    ('Rícina', 'Vegetal'),
    ('Queratina', 'Vegetal'),
    ('Pectina', 'Vegetal')
]

# Se contruye el dataframe a partir del diccionario
proteinas_df = pd.DataFrame(proteinas_dic)

# Se imprime el dataframe
proteinas_df

nombre     tipo
0     Gluten  Vegetal
1   Gelatina   Animal
2  Queratina  Vegetal
3    Pectina  Vegetal
4   Colágeno  Vegetal

In [ ]:
El cual nos da el mismo resultado.